# Generated by Django 2.2.3 on 2019-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoritmo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='algoritmo',
            name='nombreAlgoritmo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
