# Generated by Django 2.2.3 on 2019-08-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0002_auto_20190807_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('idEntrenamiento', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tituloEntrenamiento', models.CharField(max_length=80)),
                ('foraneaAlgoritmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algoritmo.Algoritmo')),
            ],
        ),
    ]
