# Generated by Django 2.2.3 on 2019-08-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0003_entrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='rutaArchivo',
            field=models.FileField(blank=True, null=True, upload_to='Archivos/'),
        ),
    ]
