# Generated by Django 2.2.3 on 2019-08-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0006_auto_20190807_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecucion',
            name='foraneaEntrenamiento',
        ),
    ]
