# Generated by Django 2.2.3 on 2019-08-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0007_remove_ejecucion_foraneaentrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucion',
            name='foraneaEntrenamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='algoritmo.Entrenamiento'),
        ),
    ]
