# Generated by Django 2.2.3 on 2019-08-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0008_ejecucion_foraneaentrenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucion',
            name='tiempoEjecucion',
            field=models.TimeField(),
        ),
    ]
