# Generated by Django 2.2.3 on 2019-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoritmo', '0009_auto_20190808_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='archivoEntrenamiento',
            field=models.FileField(null=True, upload_to='Archivos/Entrenamiento'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tiempoEntrenamiento',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ejecucion',
            name='datoPrueba',
            field=models.FileField(null=True, upload_to='Archivos/Prueba'),
        ),
    ]
